# -*- coding: utf-8 -*-
"""SI101 Final Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6lKyo1qe927hVMlV23oDN7qRW3XxPOM

In order to access valid API key, please go to https://collegefootballdata.com/key, and follow the prompts. The API key should be sent to your email.
"""

import requests
from getpass import getpass

# Function to repeatedly prompt the user for an API key until a valid one is entered
def get_valid_api_key():
  while True:
    # Prompt the user to securely enter their API key (input is hidden)
    api_key = getpass("Enter your CFBD API key: ").strip()

    # Create headers for the API request, including the Authorization token
    headers = {
        "Authorization": f"Bearer {api_key}"
    }

    # Base URL endpoint for College Football Data API
    url = "https://api.collegefootballdata.com/games"

    # Sample query parameters used to test if the API key works
    # (any valid request will confirm authentication)
    params = {
        "year": 2023,
        "week": 1
    }

    try:
      # Send a GET request to the API with headers and parameters
      response = requests.get(url, headers=headers, params=params)

      # Check if the response status code indicates success (200 OK)
      if response.status_code == 200:
        print("API key validated successfully\n")
        return api_key
      else:
        # If the key is invalid or unauthorized, prompt the user again
        print("Invalid API key. Please try again.\n")

    except requests.exceptions.RequestException:
      # Handle any network-related errors (e.g., no internet, timeout)
      print("Network error. Try again\n")

import requests

# Function used to fetch all game data for a given year and week
def fetch_games_data(api_key, year, week):
  # API endpoint for retrieving game data
  url = "https://api.collegefootballdata.com/games"

  # Headers including the API key for authentication
  headers = {
    "Authorization": f"Bearer {api_key}"
  }

  # Query parameters specifying which games to retrieve
  params = {
    "year": year,
    "week": week
  }

  try:
    # Inform the user that data fetching has started
    print("Fetching game data...\n")

    # Send a GET request to the API
    response = requests.get(url, headers=headers, params=params)

    # If the request is successful (status code 200 OK)
    if response.status_code == 200:
      # Parse the JSON response into Python data
      data = response.json()

      # Check if no games were returned for the given inputs
      if len(data) == 0:
        print("No games found for that year/week.\n")
        return [] # Return empty list if no data

      # Successfully retrieved game data
      print("Game data fetched successfully.\n")
      return data

    # If the API key is invalid or unauthorized
    elif response.status_code == 401:
      print("Unauthorized. Please check your API key.\n")
      return []

    # Handle all other HTTP errors
    else:
      print(f"Error: {response.status_code} - Unable to fetch data.\n")
      return []

  # Handle request timeout specifically
  except requests.exceptions.Timeout:
    print("Request timed out. Please try again later.\n")
    return []

  # Handle general network-related errors
  except requests.exceptions.RequestException:
    print("Network error while fetching data.\n")
    return []

# Function used to filter and return games that involve a user-specified team
def get_games_by_team(games, team):
  # List to store games that match the given team
  matching_games = []

  # Loop through each game in the provided list of games
  for game in games:
    # Extract and normalize the home team name (remove whitespace and convert to lowercase)
    home_team = game.get("homeTeam", "").strip().lower()

    # Extract and normalize the away team name (remove whitespace and convert to lowercase)
    away_team = game.get("awayTeam", "").strip().lower()

    # Check if the input team matches either the home or away team
    if team.lower() == home_team or team.lower() == away_team:
      # If a match is found, add the game to the matching list
      matching_games.append(game)

  # If no matching games were found, notify the user
  if len(matching_games) == 0:
    print(f"No games found for team {team}.\n")
  else:
    # Otherwise, display how many matching games were found
    print(f"Found {len(matching_games)} game(s) for {team}.\n")

  # Return the list of matching games (may be empty)
  return matching_games

# Function to calculate and display a team's performance for a given week
def team_week_stats(team_games, team, week):
  # Initialize counters for wins, losses, and total points scored
  wins = 0
  losses = 0
  points_scored = 0

  # Print a formatted header for the weekly summary
  print(f"\n{team.title()} Weekly Summary - Week {week}")
  print("-" * 50)

  # Loop through each game involving the team
  for game in team_games:
    # Extract team names and scores from the game data
    home_team = game.get("homeTeam", "")
    away_team = game.get("awayTeam", "")
    home_points = game.get("homePoints")
    away_points = game.get("awayPoints")

    # Skip games where scores are not available (e.g., not yet played)
    if home_points is None or away_points is None:
      continue

    # Determine if the selected team is the home or away team
    if home_team.lower() == team.lower():
      opponent = away_team
      team_points = home_points
      opp_points = away_points
    else:
      opponent = home_team
      team_points = away_points
      opp_points = home_points

    # Add this game's points to the total points scored
    points_scored += team_points

    # Determine if the team won or lost and update counters
    if team_points > opp_points:
      print(f"W vs {opponent} ({team_points}-{opp_points})")
      wins += 1
    else:
      print(f"L vs {opponent} ({team_points}-{opp_points})")
      losses += 1

  # Print a summary of results
  print("-" * 50)
  print(f"Games Played: {len(team_games)}")
  print(f"Wins: {wins} | Losses: {losses}")
  print(f"Total Points Scored: {points_scored}")

import requests

# Function to fetch all player statistics for a specific game, year, and week
def fetch_player_stats(api_key, game_id, year, week):
  # API endpoint for retrieving player stats from a game
  url = "https://api.collegefootballdata.com/games/players"

  # Headers including the API key for authentication
  headers = {
    "Authorization": f"Bearer {api_key}"
  }

  # Query parameters specifying which game's player stats to retrieve
  params = {
    "gameId": game_id,
    "year": year,
    "week": week
  }

  try:
    # Inform the user that the request is in progress
    print("Fetching player stats...")

    # Send a GET request to the API with a timeout of 10 seconds
    response = requests.get(url, headers=headers, params=params, timeout = 10)

    # If the request is successful (status code 200 OK)
    if response.status_code == 200:
      # Parse the JSON response into Python data
      data = response.json()

      # Check if no player stats were returned
      if len(data) == 0:
        print("No player stats found.")
        return []  # Return empty list if no data

      # Successfully retrieved player stats
      print("Player stats fetched successfully\n")
      return data

    else:
      # Handle non-200 responses by printing the error message from the API
      print("Error:", response.text)
      return []

  # Handle any network-related errors (e.g., timeout, connection issues)
  except requests.exceptions.RequestException:
        print("Network error while fetching player stats.")
        return []

# Function to filter player stats data so it only includes the two teams in a given game
def filter_player_stats_by_teams(player_data, game):
  # Extract and normalize the home and away team names from the game
  home_team = game.get("homeTeam", "").lower()
  away_team = game.get("awayTeam", "").lower()

  # List to store filtered team data
  filtered = []

  # Set to track which teams have already been added (prevents duplicates)
  seen_teams = set()

  # Loop through each game block in the player data
  for game_block in player_data:
    # Each game block may contain multiple teams
    for team in game_block.get("teams", []):
      # Extract and normalize the team name
      team_name = team.get("team", "").strip().lower()

      # Check if the team matches either the home or away team
      # and has not already been added
      if (team_name == home_team or team_name == away_team) and team_name not in seen_teams:
        # Add the matching team to the filtered list
        filtered.append(team)

        # Mark this team as seen to avoid duplicates
        seen_teams.add(team_name)

  # Return the filtered list of team stats
  return filtered

# Function to determine statistical leaders (passing, rushing, receiving) from filtered data
def get_stat_leaders(filtered_data):
  # Initialize leaders dictionary with default values
  # Each category stores a tuple: (player_name, stat_value)
  leaders = {
      "passing": ("None", 0),
      "rushing": ("None", 0),
      "receiving": ("None", 0)
  }

  # Loop through each team's data in the filtered dataset
  for team in filtered_data:
    # Each team contains multiple statistical categories (e.g., passing, rushing)
    for category in team.get("categories", []):
      # Name of the category
      category_name = category.get("name")

      # Each category contains different stat types (e.g., YDS, TDs, etc.)
      for stat_type in category.get("types", []):
        stat_name = stat_type.get("name")

        # Only consider yardage stats ("YDS")
        if stat_name != "YDS":
          continue

        # Loop through each athlete in the stat type
        for athlete in stat_type.get("athletes", []):
          name = athlete.get("name")
          stat = athlete.get("stat")

          # Attempt to convert stat to an integer
          try:
            stat = int(stat)
          except:
            continue

          # Update passing leader if this stat is higher
          if category_name == "passing":
            if stat > leaders["passing"][1]:
              leaders["passing"] = (name, stat)

          # Update rushing leader if this stat is higher
          elif category_name == "rushing":
            if stat > leaders["rushing"][1]:
              leaders["rushing"] = (name, stat)

          # Update receiving leader if this stat is higher
          elif category_name == "receiving":
            if stat > leaders["receiving"][1]:
              leaders["receiving"] = (name, stat)

  # Return the dictionary containing stat leaders for each category
  return leaders

# Function to display the top statistical leaders for passing, rushing, and receiving
def display_stat_leaders(leaders):
  # Print a header for the stat leaders section
  print("Stat Leaders")
  print("-" * 30)

  # Display the top passing leader
  # leaders['passing'] is expected to be a tuple/list: (player_name, yards)
  print(f"Passing: {leaders['passing'][0]} ({leaders['passing'][1]} yards)")

  # Display the top rushing leader
  # leaders['rushing'] is expected to be a tuple/list: (player_name, yards)
  print(f"Rushing: {leaders['rushing'][0]} ({leaders['rushing'][1]} yards)")

  # Display the top receiving leader
  # leaders['receiving'] is expected to be a tuple/list: (player_name, yards)
  print(f"Receiving: {leaders['receiving'][0]} ({leaders['receiving'][1]} yards)")

# Function to fetch team records data for a given year
def get_records_data(api_key, year):
  # Headers including the API key for authentication
  headers = {
    "Authorization": f"Bearer {api_key}"
  }

  # API endpoint for retrieving team records
  url = "https://api.collegefootballdata.com/records"

  # Query parameters specifying the year of interest
  params = {"year": year}

  try:
    # Send a GET request to the API with a timeout of 10 seconds
    response = requests.get(url, headers=headers, params=params, timeout=10)

    # Check if the request was successful (status code 200 OK)
    if response.status_code == 200:
      return response.json()
    else:
      # Handle non-200 responses by printing the error status code
      print(f"Error fetching records: {response.status_code}")
      return []

  # Handle any network-related errors (e.g., timeout, connection issues)
  except requests.exceptions.RequestException:
    print("Network error while fetching records.")
    return []

# Function to find and return the conference for a specific team
def get_team_conference(data, team):
  # Normalize the input team name (remove whitespace and convert to lowercase)
  team = team.strip().lower()

  # Loop through each record in the dataset (likely team information)
  for record in data:
    # Extract and normalize the team name from the record
    team_name = record.get("team", "").strip().lower()

    # Extract the conference, defaulting to "Unknown" if not present
    conference = record.get("conference", "Unknown").strip()

    # Check if the current record matches the requested team
    if team_name == team:
      return conference   # Return the matching team's conference

  # If no match is found, return a message indicating failure
  return "Team not found."

# Function to determine the conferences of the home and away teams for a given game
def get_game_conferences(data, game):
  # Extract and normalize the home and away team names from the game
  home_team = game.get("homeTeam", "").strip().lower()
  away_team = game.get("awayTeam", "").strip().lower()

  # Initialize conference values with a default of "Unknown"
  home_conf = "Unknown"
  away_conf = "Unknown"

  # Loop through each record in the provided data (likely team info)
  for record in data:
    # Extract and normalize the team name and conference
    team_name = record.get("team", "").strip().lower()
    conference = record.get("conference", "Unknown").strip()

    # Check if the record matches the home team
    if team_name == home_team:
      home_conf = conference
    # Check if the record matches the away team
    elif team_name == away_team:
      away_conf = conference

  # Return both conferences as a tuple (home_conf, away_conf)
  return home_conf, away_conf

+import pprint

# Main function that drives the entire program
def main():
  # Prompt user for a valid API key
  api_key = get_valid_api_key()

  # Loop until a valid year is entered or user quits
  while True:
    user_input = input("Enter year (or 'q' to quit): ").strip()
    if user_input.lower() == "q":
        print("Exiting program.")
        return
    try:
      year = int(user_input)
      # Validate year range
      if 1869 <= year <= 2100:
        break
      else:
        print("Please enter a year between 1869 and 2100.")

    except ValueError:
      # Handle non-numeric input
      print("Year must be a number. Try again.")

  # Fetch team records data for the given year
  records_data = get_records_data(api_key, year)

  # Create a set of valid team names for input validation
  valid_teams = {record.get("team", "").strip().lower() for record in records_data}

  # Loop until a valid team name is entered or user quits
  while True:
    team_input = input("Enter team name (or 'q' to quit): ").strip()
    if team_input.lower() == "q":
      print("Exiting program.")
      return
    # Check if input matches a valid team
    if team_input.lower() in valid_teams:
      team = team_input
      break
    else:
      print("Invalid team name. Please enter the full official team name (e.g., 'Michigan').")

  # Loop until a valid week is entered or user quits
  while True:
    user_input = input("Enter week (or 'q' to quit): ").strip()
    if user_input.lower() == "q":
      print("Exiting program.")
      return
    try:
      week = int(user_input)
      # Validate week range
      if 1 <= week <= 20:
        break
      else:
        print("Please enter a week between 1 and 20.")

    except ValueError:
      # Handle non-numeric input
      print("Week must be a number. Try again.")

  # Fetch game data for the specified year and week
  games = fetch_games_data(api_key, year, week)

  # Exit if no games were found
  if not games:
    print("No data available for that week. Exiting program.")
    return

  # Filter games to only those involving the selected team
  team_games = get_games_by_team(games, team)

  # Exit if no games were found for that team
  if not team_games:
    print(f"No games found for {team} in Week {week}.")
    return

  # Select the first game from the filtered list
  game = team_games[0]

  # Print the game ID
  print("Game ID:", game.get("id"))

  # Get conference information for both teams
  home_conf, away_conf = get_game_conferences(records_data, game)

  # Display matchup with conference info
  print(f"{game.get('homeTeam')} ({home_conf}) vs {game.get('awayTeam')} ({away_conf})")

  # Display weekly stats summary for the selected team
  team_week_stats([game], team, week)

  # Extract game ID for player stats request
  game_id = game.get("id")
  print()

  # Fetch player statistics for the selected game
  player_data = fetch_player_stats(api_key, game_id, year, week)

  # Filter player stats to only include the two teams in the game
  filtered_data = filter_player_stats_by_teams(player_data, game)

  # If no player stats are available, notify the user
  if not filtered_data:
    print("No stats available for this game.")
  else:
    # Determine stat leaders from the filtered data
    leaders = get_stat_leaders(filtered_data)

    # Display the stat leaders
    display_stat_leaders(leaders)

# Entry point of the program
if __name__ == "__main__":
    main()